/**
 * Profile RPC wrappers — Cursor-only.
 * Lovable: do not edit this file.
 */
import { getSupabaseClient } from "@/integrations/supabase/client";

export async function completeOnboardingStep(step: number) {
  const supabase = getSupabaseClient();
  if (!supabase) throw new Error("Supabase not configured");
  const { data, error } = await supabase.rpc("complete_onboarding_step", { p_step: step });
  if (error) throw error;
  return data;
}
