/**
 * Wallet RPC wrappers — Cursor-only SSOT for Supabase money paths.
 *
 * Features must NOT call supabase.rpc() directly; use these functions.
 * Lovable: do not edit this file.
 */
import { getSupabaseClient } from "@/integrations/supabase/client";

export async function debitPhonForBet(amount: number, game: string, roundId: string) {
  const supabase = getSupabaseClient();
  const { data, error } = await supabase.rpc("debit_phon_for_bet", {
    p_amount: amount,
    p_game: game,
    p_round_id: roundId,
  });
  if (error) throw error;
  return data;
}
