/**
 * Wallet RPC wrappers — Cursor-only SSOT for Supabase money paths.
 *
 * Features must NOT call supabase.rpc() directly; use these functions.
 * Lovable: do not edit this file.
 */
import { getSupabaseClient } from "@/integrations/supabase/client";

// TODO: implement debit_phon_for_bet RPC when real-mode betting ships
export async function debitPhonForBet(_amount: number, _game: string, _roundId: string) {
  const supabase = getSupabaseClient();
  if (!supabase) throw new Error("Supabase not configured");
  throw new Error("debit_phon_for_bet RPC not implemented — Cursor task");
}
