/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WithdrawalIndexRouteImport } from './routes/withdrawal/index'
import { Route as DepositIndexRouteImport } from './routes/deposit/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WithdrawalPhonRouteImport } from './routes/withdrawal/phon'
import { Route as WithdrawalCryptoRouteImport } from './routes/withdrawal/crypto'
import { Route as DepositGiftRouteImport } from './routes/deposit/gift'
import { Route as DepositCryptoRouteImport } from './routes/deposit/crypto'
import { Route as DepositBankRouteImport } from './routes/deposit/bank'
import { Route as AdminNoticeRouteImport } from './routes/admin/notice'
import { Route as AdminEventRouteImport } from './routes/admin/event'
import { Route as AppNoticeRouteImport } from './routes/_app/notice'
import { Route as AppMyRouteImport } from './routes/_app/my'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as AppEventRouteImport } from './routes/_app/event'
import { Route as AppEarnRouteImport } from './routes/_app/earn'
import { Route as AppNoticeIdRouteImport } from './routes/_app/notice.$id'
import { Route as AppGamesWheelRouteImport } from './routes/_app/games.wheel'
import { Route as AppGamesPlinkoRouteImport } from './routes/_app/games.plinko'
import { Route as AppGamesMinesRouteImport } from './routes/_app/games.mines'
import { Route as AppGamesLimboRouteImport } from './routes/_app/games.limbo'
import { Route as AppGamesDiceRouteImport } from './routes/_app/games.dice'
import { Route as AppGamesCrashRouteImport } from './routes/_app/games.crash'
import { Route as AppExchangeSymbolRouteImport } from './routes/_app/exchange.$symbol'
import { Route as AppEventIdRouteImport } from './routes/_app/event.$id'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalIndexRoute = WithdrawalIndexRouteImport.update({
  id: '/withdrawal/',
  path: '/withdrawal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositIndexRoute = DepositIndexRouteImport.update({
  id: '/deposit/',
  path: '/deposit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalPhonRoute = WithdrawalPhonRouteImport.update({
  id: '/withdrawal/phon',
  path: '/withdrawal/phon',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawalCryptoRoute = WithdrawalCryptoRouteImport.update({
  id: '/withdrawal/crypto',
  path: '/withdrawal/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositGiftRoute = DepositGiftRouteImport.update({
  id: '/deposit/gift',
  path: '/deposit/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositCryptoRoute = DepositCryptoRouteImport.update({
  id: '/deposit/crypto',
  path: '/deposit/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositBankRoute = DepositBankRouteImport.update({
  id: '/deposit/bank',
  path: '/deposit/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticeRoute = AdminNoticeRouteImport.update({
  id: '/admin/notice',
  path: '/admin/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventRoute = AdminEventRouteImport.update({
  id: '/admin/event',
  path: '/admin/event',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNoticeRoute = AppNoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMyRoute = AppMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventRoute = AppEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEarnRoute = AppEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNoticeIdRoute = AppNoticeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNoticeRoute,
} as any)
const AppGamesWheelRoute = AppGamesWheelRouteImport.update({
  id: '/games/wheel',
  path: '/games/wheel',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGamesPlinkoRoute = AppGamesPlinkoRouteImport.update({
  id: '/games/plinko',
  path: '/games/plinko',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGamesMinesRoute = AppGamesMinesRouteImport.update({
  id: '/games/mines',
  path: '/games/mines',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGamesLimboRoute = AppGamesLimboRouteImport.update({
  id: '/games/limbo',
  path: '/games/limbo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGamesDiceRoute = AppGamesDiceRouteImport.update({
  id: '/games/dice',
  path: '/games/dice',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGamesCrashRoute = AppGamesCrashRouteImport.update({
  id: '/games/crash',
  path: '/games/crash',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExchangeSymbolRoute = AppExchangeSymbolRouteImport.update({
  id: '/exchange/$symbol',
  path: '/exchange/$symbol',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventIdRoute = AppEventIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEventRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/earn': typeof AppEarnRoute
  '/event': typeof AppEventRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/my': typeof AppMyRoute
  '/notice': typeof AppNoticeRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/notice': typeof AdminNoticeRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/crypto': typeof DepositCryptoRoute
  '/deposit/gift': typeof DepositGiftRoute
  '/withdrawal/crypto': typeof WithdrawalCryptoRoute
  '/withdrawal/phon': typeof WithdrawalPhonRoute
  '/admin/': typeof AdminIndexRoute
  '/deposit/': typeof DepositIndexRoute
  '/withdrawal/': typeof WithdrawalIndexRoute
  '/event/$id': typeof AppEventIdRoute
  '/exchange/$symbol': typeof AppExchangeSymbolRoute
  '/games/crash': typeof AppGamesCrashRoute
  '/games/dice': typeof AppGamesDiceRoute
  '/games/limbo': typeof AppGamesLimboRoute
  '/games/mines': typeof AppGamesMinesRoute
  '/games/plinko': typeof AppGamesPlinkoRoute
  '/games/wheel': typeof AppGamesWheelRoute
  '/notice/$id': typeof AppNoticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/earn': typeof AppEarnRoute
  '/event': typeof AppEventRouteWithChildren
  '/feed': typeof AppFeedRoute
  '/my': typeof AppMyRoute
  '/notice': typeof AppNoticeRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/notice': typeof AdminNoticeRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/crypto': typeof DepositCryptoRoute
  '/deposit/gift': typeof DepositGiftRoute
  '/withdrawal/crypto': typeof WithdrawalCryptoRoute
  '/withdrawal/phon': typeof WithdrawalPhonRoute
  '/admin': typeof AdminIndexRoute
  '/deposit': typeof DepositIndexRoute
  '/withdrawal': typeof WithdrawalIndexRoute
  '/event/$id': typeof AppEventIdRoute
  '/exchange/$symbol': typeof AppExchangeSymbolRoute
  '/games/crash': typeof AppGamesCrashRoute
  '/games/dice': typeof AppGamesDiceRoute
  '/games/limbo': typeof AppGamesLimboRoute
  '/games/mines': typeof AppGamesMinesRoute
  '/games/plinko': typeof AppGamesPlinkoRoute
  '/games/wheel': typeof AppGamesWheelRoute
  '/notice/$id': typeof AppNoticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/transfer': typeof TransferRoute
  '/_app/earn': typeof AppEarnRoute
  '/_app/event': typeof AppEventRouteWithChildren
  '/_app/feed': typeof AppFeedRoute
  '/_app/my': typeof AppMyRoute
  '/_app/notice': typeof AppNoticeRouteWithChildren
  '/admin/event': typeof AdminEventRoute
  '/admin/notice': typeof AdminNoticeRoute
  '/deposit/bank': typeof DepositBankRoute
  '/deposit/crypto': typeof DepositCryptoRoute
  '/deposit/gift': typeof DepositGiftRoute
  '/withdrawal/crypto': typeof WithdrawalCryptoRoute
  '/withdrawal/phon': typeof WithdrawalPhonRoute
  '/admin/': typeof AdminIndexRoute
  '/deposit/': typeof DepositIndexRoute
  '/withdrawal/': typeof WithdrawalIndexRoute
  '/_app/event/$id': typeof AppEventIdRoute
  '/_app/exchange/$symbol': typeof AppExchangeSymbolRoute
  '/_app/games/crash': typeof AppGamesCrashRoute
  '/_app/games/dice': typeof AppGamesDiceRoute
  '/_app/games/limbo': typeof AppGamesLimboRoute
  '/_app/games/mines': typeof AppGamesMinesRoute
  '/_app/games/plinko': typeof AppGamesPlinkoRoute
  '/_app/games/wheel': typeof AppGamesWheelRoute
  '/_app/notice/$id': typeof AppNoticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/transfer'
    | '/earn'
    | '/event'
    | '/feed'
    | '/my'
    | '/notice'
    | '/admin/event'
    | '/admin/notice'
    | '/deposit/bank'
    | '/deposit/crypto'
    | '/deposit/gift'
    | '/withdrawal/crypto'
    | '/withdrawal/phon'
    | '/admin/'
    | '/deposit/'
    | '/withdrawal/'
    | '/event/$id'
    | '/exchange/$symbol'
    | '/games/crash'
    | '/games/dice'
    | '/games/limbo'
    | '/games/mines'
    | '/games/plinko'
    | '/games/wheel'
    | '/notice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/transfer'
    | '/earn'
    | '/event'
    | '/feed'
    | '/my'
    | '/notice'
    | '/admin/event'
    | '/admin/notice'
    | '/deposit/bank'
    | '/deposit/crypto'
    | '/deposit/gift'
    | '/withdrawal/crypto'
    | '/withdrawal/phon'
    | '/admin'
    | '/deposit'
    | '/withdrawal'
    | '/event/$id'
    | '/exchange/$symbol'
    | '/games/crash'
    | '/games/dice'
    | '/games/limbo'
    | '/games/mines'
    | '/games/plinko'
    | '/games/wheel'
    | '/notice/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/transfer'
    | '/_app/earn'
    | '/_app/event'
    | '/_app/feed'
    | '/_app/my'
    | '/_app/notice'
    | '/admin/event'
    | '/admin/notice'
    | '/deposit/bank'
    | '/deposit/crypto'
    | '/deposit/gift'
    | '/withdrawal/crypto'
    | '/withdrawal/phon'
    | '/admin/'
    | '/deposit/'
    | '/withdrawal/'
    | '/_app/event/$id'
    | '/_app/exchange/$symbol'
    | '/_app/games/crash'
    | '/_app/games/dice'
    | '/_app/games/limbo'
    | '/_app/games/mines'
    | '/_app/games/plinko'
    | '/_app/games/wheel'
    | '/_app/notice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  TransferRoute: typeof TransferRoute
  AdminEventRoute: typeof AdminEventRoute
  AdminNoticeRoute: typeof AdminNoticeRoute
  DepositBankRoute: typeof DepositBankRoute
  DepositCryptoRoute: typeof DepositCryptoRoute
  DepositGiftRoute: typeof DepositGiftRoute
  WithdrawalCryptoRoute: typeof WithdrawalCryptoRoute
  WithdrawalPhonRoute: typeof WithdrawalPhonRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DepositIndexRoute: typeof DepositIndexRoute
  WithdrawalIndexRoute: typeof WithdrawalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal/': {
      id: '/withdrawal/'
      path: '/withdrawal'
      fullPath: '/withdrawal/'
      preLoaderRoute: typeof WithdrawalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/': {
      id: '/deposit/'
      path: '/deposit'
      fullPath: '/deposit/'
      preLoaderRoute: typeof DepositIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal/phon': {
      id: '/withdrawal/phon'
      path: '/withdrawal/phon'
      fullPath: '/withdrawal/phon'
      preLoaderRoute: typeof WithdrawalPhonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdrawal/crypto': {
      id: '/withdrawal/crypto'
      path: '/withdrawal/crypto'
      fullPath: '/withdrawal/crypto'
      preLoaderRoute: typeof WithdrawalCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/gift': {
      id: '/deposit/gift'
      path: '/deposit/gift'
      fullPath: '/deposit/gift'
      preLoaderRoute: typeof DepositGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/crypto': {
      id: '/deposit/crypto'
      path: '/deposit/crypto'
      fullPath: '/deposit/crypto'
      preLoaderRoute: typeof DepositCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit/bank': {
      id: '/deposit/bank'
      path: '/deposit/bank'
      fullPath: '/deposit/bank'
      preLoaderRoute: typeof DepositBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notice': {
      id: '/admin/notice'
      path: '/admin/notice'
      fullPath: '/admin/notice'
      preLoaderRoute: typeof AdminNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/event': {
      id: '/admin/event'
      path: '/admin/event'
      fullPath: '/admin/event'
      preLoaderRoute: typeof AdminEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notice': {
      id: '/_app/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof AppNoticeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/my': {
      id: '/_app/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AppMyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/event': {
      id: '/_app/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AppEventRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/earn': {
      id: '/_app/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof AppEarnRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/notice/$id': {
      id: '/_app/notice/$id'
      path: '/$id'
      fullPath: '/notice/$id'
      preLoaderRoute: typeof AppNoticeIdRouteImport
      parentRoute: typeof AppNoticeRoute
    }
    '/_app/games/wheel': {
      id: '/_app/games/wheel'
      path: '/games/wheel'
      fullPath: '/games/wheel'
      preLoaderRoute: typeof AppGamesWheelRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/games/plinko': {
      id: '/_app/games/plinko'
      path: '/games/plinko'
      fullPath: '/games/plinko'
      preLoaderRoute: typeof AppGamesPlinkoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/games/mines': {
      id: '/_app/games/mines'
      path: '/games/mines'
      fullPath: '/games/mines'
      preLoaderRoute: typeof AppGamesMinesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/games/limbo': {
      id: '/_app/games/limbo'
      path: '/games/limbo'
      fullPath: '/games/limbo'
      preLoaderRoute: typeof AppGamesLimboRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/games/dice': {
      id: '/_app/games/dice'
      path: '/games/dice'
      fullPath: '/games/dice'
      preLoaderRoute: typeof AppGamesDiceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/games/crash': {
      id: '/_app/games/crash'
      path: '/games/crash'
      fullPath: '/games/crash'
      preLoaderRoute: typeof AppGamesCrashRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/exchange/$symbol': {
      id: '/_app/exchange/$symbol'
      path: '/exchange/$symbol'
      fullPath: '/exchange/$symbol'
      preLoaderRoute: typeof AppExchangeSymbolRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/event/$id': {
      id: '/_app/event/$id'
      path: '/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AppEventIdRouteImport
      parentRoute: typeof AppEventRoute
    }
  }
}

interface AppEventRouteChildren {
  AppEventIdRoute: typeof AppEventIdRoute
}

const AppEventRouteChildren: AppEventRouteChildren = {
  AppEventIdRoute: AppEventIdRoute,
}

const AppEventRouteWithChildren = AppEventRoute._addFileChildren(
  AppEventRouteChildren,
)

interface AppNoticeRouteChildren {
  AppNoticeIdRoute: typeof AppNoticeIdRoute
}

const AppNoticeRouteChildren: AppNoticeRouteChildren = {
  AppNoticeIdRoute: AppNoticeIdRoute,
}

const AppNoticeRouteWithChildren = AppNoticeRoute._addFileChildren(
  AppNoticeRouteChildren,
)

interface AppRouteRouteChildren {
  AppEarnRoute: typeof AppEarnRoute
  AppEventRoute: typeof AppEventRouteWithChildren
  AppFeedRoute: typeof AppFeedRoute
  AppMyRoute: typeof AppMyRoute
  AppNoticeRoute: typeof AppNoticeRouteWithChildren
  AppExchangeSymbolRoute: typeof AppExchangeSymbolRoute
  AppGamesCrashRoute: typeof AppGamesCrashRoute
  AppGamesDiceRoute: typeof AppGamesDiceRoute
  AppGamesLimboRoute: typeof AppGamesLimboRoute
  AppGamesMinesRoute: typeof AppGamesMinesRoute
  AppGamesPlinkoRoute: typeof AppGamesPlinkoRoute
  AppGamesWheelRoute: typeof AppGamesWheelRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEarnRoute: AppEarnRoute,
  AppEventRoute: AppEventRouteWithChildren,
  AppFeedRoute: AppFeedRoute,
  AppMyRoute: AppMyRoute,
  AppNoticeRoute: AppNoticeRouteWithChildren,
  AppExchangeSymbolRoute: AppExchangeSymbolRoute,
  AppGamesCrashRoute: AppGamesCrashRoute,
  AppGamesDiceRoute: AppGamesDiceRoute,
  AppGamesLimboRoute: AppGamesLimboRoute,
  AppGamesMinesRoute: AppGamesMinesRoute,
  AppGamesPlinkoRoute: AppGamesPlinkoRoute,
  AppGamesWheelRoute: AppGamesWheelRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  TransferRoute: TransferRoute,
  AdminEventRoute: AdminEventRoute,
  AdminNoticeRoute: AdminNoticeRoute,
  DepositBankRoute: DepositBankRoute,
  DepositCryptoRoute: DepositCryptoRoute,
  DepositGiftRoute: DepositGiftRoute,
  WithdrawalCryptoRoute: WithdrawalCryptoRoute,
  WithdrawalPhonRoute: WithdrawalPhonRoute,
  AdminIndexRoute: AdminIndexRoute,
  DepositIndexRoute: DepositIndexRoute,
  WithdrawalIndexRoute: WithdrawalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
